### ISSUE TITLE
IOError/404 on image when editing/adding certain issues on beta (but not locally)

### ISSUE THREAD

**Issue by handrews** [GrandComicsDatabase/gcd-django#148]
Example:

Internal Server Error: /series/93839/add_issues/year/
Traceback (most recent call last):
[...]
    return view_func(request, *args, **kwargs)
  File "/var/www/gcd-django-17/apps/oi/views.py", line 2124, in add_issues
    return _display_bulk_issue_form(request, series, form, method)
  File "/var/www/gcd-django-17/apps/oi/views.py", line 2276, in _display_bulk_issue_form
    context_instance=RequestContext(request))
  File "/var/www/gcd-django-17/apps/oi/views.py", line 95, in oi_render_to_response
    return render_to_response(template_name, context, context_instance)
[...]
  File "/var/www/gcd-django-17/apps/oi/forms.py", line 1442, in as_table
    return super(base, self).as_table()
[...]
  File "/var/www/gcd-django-17/apps/oi/forms.py", line 878, in render_option
    escape(option_value), selected_html, url, brand.emblem.icon.width,
  File "/opt/env/gcd_django_17/lib/python2.7/site-packages/django/core/files/images.py", line 17, in _get_width
    return self._get_image_dimensions()[0]
  File "/opt/env/gcd_django_17/lib/python2.7/site-packages/django/core/files/images.py", line 27, in _get_image_dimensions
    self.open()
  File "/opt/env/gcd_django_17/lib/python2.7/site-packages/django/db/models/fields/files.py", line 79, in open
    self.file.open(mode)
  File "/opt/env/gcd_django_17/lib/python2.7/site-packages/django/db/models/fields/files.py", line 49, in _get_file
    self._file = self.storage.open(self.name, 'rb')
  File "/opt/env/gcd_django_17/lib/python2.7/site-packages/django/core/files/storage.py", line 35, in open
    return self._open(name, mode)
  File "/opt/env/gcd_django_17/lib/python2.7/site-packages/django/core/files/storage.py", line 172, in _open
    return File(open(self.path(name), mode))
IOError: [Errno 2] No such file or directory: u'/var/www/gcd-django-17/site_media/cache/img/gcd/generic_images/29/29116_icon.jpg'

**Comment by handrews** [comment]
Jochen re-sync'd the covers and this is now fixed.  It was just a state mismatch between the DB and the filesystem.
