### ISSUE TITLE
password reminder link gives error

### ISSUE THREAD

**Issue by jochengcd** [GrandComicsDatabase/gcd-django#152]
Internal Server Error: /accounts/forgot/
Traceback (most recent call last):
  File "/opt/env/gcd_django_17/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/env/gcd_django_17/lib/python2.7/site-packages/django/utils/decorators.py", line 105, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/opt/env/gcd_django_17/lib/python2.7/site-packages/django/contrib/auth/views.py", line 148, in password_reset
    post_reset_redirect = resolve_url(post_reset_redirect)
  File "/opt/env/gcd_django_17/lib/python2.7/site-packages/django/shortcuts.py", line 165, in resolve_url
    return urlresolvers.reverse(to, args=args, kwargs=kwargs)
  File "/opt/env/gcd_django_17/lib/python2.7/site-packages/django/core/urlresolvers.py", line 551, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/opt/env/gcd_django_17/lib/python2.7/site-packages/django/core/urlresolvers.py", line 468, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'done' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []

**Comment by handrews** [comment]
I just discovered and fixed this literally about three hours ago while splitting the account code out into a new app :-)
